(function(){
'use strict';
var reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
var touch=window.matchMedia('(hover: none)').matches;

/* FILM GRAIN */
if(!reduced){var grain=document.getElementById('grain');if(grain){var gCtx=grain.getContext('2d');var gFrame=0;function resizeGrain(){grain.width=window.innerWidth;grain.height=window.innerHeight;}resizeGrain();window.addEventListener('resize',resizeGrain,{passive:true});function drawGrain(){gFrame++;if(gFrame%3===0){var w=grain.width,h=grain.height;var img=gCtx.createImageData(w,h);var d=img.data;for(var i=0;i<d.length;i+=4){var v=(Math.random()*255)|0;d[i]=d[i+1]=d[i+2]=v;d[i+3]=18;}gCtx.putImageData(img,0,0);}requestAnimationFrame(drawGrain);}drawGrain();}}

/* WEBGL PARTICLES */
if(!reduced){var hCanvas=document.getElementById('hero-canvas');if(hCanvas){var gl=hCanvas.getContext('webgl')||hCanvas.getContext('experimental-webgl');if(gl){var NUM=160;var vs='attribute vec2 a;uniform vec2 u;uniform float t;void main(){vec2 p=a;p.y=mod(p.y+t*0.00018*(0.5+a.x*0.3),1.0);p.x+=sin(t*0.0004+a.y*6.28)*0.008;p+=u*0.04*(1.0-length(p-0.5)*2.0);gl_Position=vec4(p*2.0-1.0,0.0,1.0);gl_PointSize=1.5;}';var fs='precision lowp float;void main(){float d=length(gl_PointCoord-0.5);if(d>0.5)discard;gl_FragColor=vec4(0.847,0.545,0.247,0.35*(1.0-d*2.0));}';function mkS(type,src){var s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s;}var prog=gl.createProgram();gl.attachShader(prog,mkS(gl.VERTEX_SHADER,vs));gl.attachShader(prog,mkS(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);gl.useProgram(prog);var pts=new Float32Array(NUM*2);for(var i=0;i<NUM*2;i++)pts[i]=Math.random();var buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,pts,gl.STATIC_DRAW);var aLoc=gl.getAttribLocation(prog,'a'),uLoc=gl.getUniformLocation(prog,'u'),tLoc=gl.getUniformLocation(prog,'t');gl.enableVertexAttribArray(aLoc);gl.vertexAttribPointer(aLoc,2,gl.FLOAT,false,0,0);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);var mx=0.5,my=0.5;document.addEventListener('mousemove',function(e){mx=e.clientX/window.innerWidth;my=1-e.clientY/window.innerHeight;},{passive:true});function resizeGL(){hCanvas.width=hCanvas.offsetWidth;hCanvas.height=hCanvas.offsetHeight;gl.viewport(0,0,hCanvas.width,hCanvas.height);}resizeGL();window.addEventListener('resize',resizeGL,{passive:true});function glLoop(t){gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform2f(uLoc,mx,my);gl.uniform1f(tLoc,t);gl.drawArrays(gl.POINTS,0,NUM);requestAnimationFrame(glLoop);}requestAnimationFrame(glLoop);}}}

/* CINEMATIC INTRO */
var intro=document.getElementById('intro');if(intro){if(reduced){intro.style.display='none';document.body.classList.add('ready');}else{var scan=document.getElementById('intro-scan');var introId=document.getElementById('intro-id');var skip=document.getElementById('intro-skip');var start=null;function eIO(t){return t<0.5?2*t*t:-1+(4-2*t)*t;}function runIntro(ts){if(!start)start=ts;var el=ts-start;if(el<700){if(scan)scan.style.transform='translateY('+eIO(el/700)*100+'vh)';requestAnimationFrame(runIntro);}else{if(scan)scan.style.transform='translateY(100vh)';setTimeout(function(){if(introId){introId.style.opacity='1';introId.style.transform='translateY(0)';}},0);setTimeout(function(){intro.style.opacity='0';intro.style.transition='opacity 0.6s ease';setTimeout(function(){intro.style.display='none';document.body.classList.add('ready');startCountUps();},600);},1800);}}function dismiss(){intro.style.opacity='0';intro.style.transition='opacity 0.3s';setTimeout(function(){intro.style.display='none';document.body.classList.add('ready');startCountUps();},300);}if(skip)skip.addEventListener('click',dismiss);requestAnimationFrame(runIntro);}}else{document.body.classList.add('ready');}

/* SCROLL BAR */
var scrollBar=document.getElementById('scroll-bar');if(scrollBar){window.addEventListener('scroll',function(){var el=document.documentElement;scrollBar.style.transform='scaleX('+el.scrollTop/(el.scrollHeight-el.clientHeight)+')';},{passive:true});}

/* HERO PARALLAX */
if(!reduced){var lBg=document.getElementById('lyr-bg'),lPhoto=document.getElementById('lyr-photo'),lCopy=document.getElementById('lyr-copy'),lGlow=document.getElementById('lyr-glow');if(lBg||lPhoto||lCopy){var tx=0,ty=0,cx=0,cy=0;document.addEventListener('mousemove',function(e){tx=(e.clientX/window.innerWidth-0.5)*2;ty=(e.clientY/window.innerHeight-0.5)*2;},{passive:true});var scrollY=0;window.addEventListener('scroll',function(){scrollY=window.scrollY;},{passive:true});function heroParallax(){cx+=(tx-cx)*0.055;cy+=(ty-cy)*0.055;var hero=document.getElementById('hero');if(hero){var r=hero.getBoundingClientRect();if(r.bottom>0&&r.top<window.innerHeight){if(lBg)lBg.style.transform='translateZ(-400px) scale(1.5) translateX('+(cx*-12)+'px) translateY('+(cy*-8+scrollY*0.3)+'px)';if(lPhoto)lPhoto.style.transform='translateX('+(cx*14)+'px) translateY('+(cy*8+scrollY*0.15)+'px)';if(lCopy)lCopy.style.transform='translateX('+(cx*6)+'px) translateY('+(cy*4+scrollY*0.05)+'px)';if(lGlow)lGlow.style.transform='translateX('+(cx*22)+'px) translateY('+(cy*16)+'px)';}}requestAnimationFrame(heroParallax);}heroParallax();}}

/* REVEALS */
var reveals=document.querySelectorAll('[data-reveal]');if(reveals.length){if(reduced){reveals.forEach(function(el){el.classList.add('vis');});}else if('IntersectionObserver' in window){var revObs=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){var delay=parseInt(entry.target.getAttribute('data-delay')||'0');setTimeout(function(){entry.target.classList.add('vis');},delay);revObs.unobserve(entry.target);}});},{threshold:0.08});reveals.forEach(function(el){revObs.observe(el);});}else{reveals.forEach(function(el){el.classList.add('vis');});}}

/* COUNT-UP */
function startCountUps(){if(reduced)return;document.querySelectorAll('[data-count]').forEach(function(el){var target=parseInt(el.getAttribute('data-count'));var dur=parseInt(el.getAttribute('data-dur')||'1200');var sfx=el.getAttribute('data-sfx')||'';var s=null;function eOC(t){return 1-Math.pow(1-t,3);}function tick(ts){if(!s)s=ts;var p=Math.min((ts-s)/dur,1);el.textContent=Math.round(eOC(p)*target)+sfx;if(p<1)requestAnimationFrame(tick);}requestAnimationFrame(tick);});}
if(document.body.classList.contains('ready'))startCountUps();

/* MAGNETIC CURSOR */
var cDot=document.getElementById('c-dot'),cRing=document.getElementById('c-ring'),cLabel=document.getElementById('c-label');if(!touch&&cDot&&cRing){document.body.style.cursor='none';var dx=0,dy=0,rx=0,ry=0;document.addEventListener('mousemove',function(e){dx=e.clientX;dy=e.clientY;},{passive:true});function cursorLoop(){rx+=(dx-rx)*0.1;ry+=(dy-ry)*0.1;cDot.style.left=dx+'px';cDot.style.top=dy+'px';cRing.style.left=rx+'px';cRing.style.top=ry+'px';if(cLabel){cLabel.style.left=rx+'px';cLabel.style.top=ry+'px';}requestAnimationFrame(cursorLoop);}cursorLoop();document.querySelectorAll('[data-cursor]').forEach(function(el){el.addEventListener('mouseenter',function(){document.body.classList.add('c-on');if(cLabel)cLabel.textContent=el.getAttribute('data-cursor');});el.addEventListener('mouseleave',function(){document.body.classList.remove('c-on');});});document.querySelectorAll('a,button').forEach(function(el){el.style.cursor='none';});}else if(cDot&&cRing){cDot.style.display='none';cRing.style.display='none';if(cLabel)cLabel.style.display='none';}

/* HAMBURGER */
var hbg=document.getElementById('hbg')||document.querySelector('.hamburger');var mobNav=document.getElementById('mob-nav')||document.querySelector('.mobile-menu');if(hbg&&mobNav){hbg.addEventListener('click',function(e){e.stopPropagation();var open=mobNav.classList.toggle('open');hbg.setAttribute('aria-expanded',open);document.body.style.overflow=open?'hidden':'';});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&mobNav.classList.contains('open')){mobNav.classList.remove('open');hbg.setAttribute('aria-expanded','false');document.body.style.overflow='';}});document.addEventListener('click',function(e){if(mobNav.classList.contains('open')&&!mobNav.contains(e.target)&&!hbg.contains(e.target)){mobNav.classList.remove('open');hbg.setAttribute('aria-expanded','false');document.body.style.overflow='';}});mobNav.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){mobNav.classList.remove('open');hbg.setAttribute('aria-expanded','false');document.body.style.overflow='';});});}

/* FAQ */
document.querySelectorAll('.faq-q').forEach(function(q){q.addEventListener('click',function(){var item=q.parentElement;var isOpen=item.classList.contains('open');document.querySelectorAll('.faq-item').forEach(function(i){i.classList.remove('open');});if(!isOpen)item.classList.add('open');});});

/* SMOOTH ANCHORS */
document.querySelectorAll('a[href^="#"]').forEach(function(a){a.addEventListener('click',function(e){var id=a.getAttribute('href').slice(1);var target=document.getElementById(id);if(target){e.preventDefault();target.scrollIntoView({behavior:reduced?'auto':'smooth'});}});});

/* TIMELINE */
var tlFill=document.getElementById('tlfill');var tlSteps=document.querySelectorAll('.tl-step');if(tlFill&&tlSteps.length&&!reduced){window.addEventListener('scroll',function(){var tl=document.querySelector('.timeline');if(!tl)return;var r=tl.getBoundingClientRect();var pct=Math.max(0,Math.min(1,(window.innerHeight-r.top)/(window.innerHeight+r.height)));tlFill.style.transform='scaleX('+pct+')';tlSteps.forEach(function(step,i){if(pct>i/tlSteps.length+0.1)step.classList.add('lit');else step.classList.remove('lit');});},{passive:true});}

})();
